#!/bin/bash
wtype 0
if [ $? -eq 0 ]
then
    sed '1,/^### DATA ###$/d' $0 | wofi --show dmenu -i | cut -d ' ' -f 1 | tr -d '\n' | wtype -
else
    sed '1,/^### DATA ###$/d' $0 | wofi --show dmenu -i | cut -d ' ' -f 1 | tr -d '\n' | wl-copy
fi
exit
### DATA ###
À capital A, grave accent
Á capital A, acute accent
Â capital A, circumflex accent
Ã capital A, tilde
Ä capital A, dieresis or umlaut mark
Å capital A, ring
Æ capital AE diphthong
Ç capital C, cedilla
È capital E, grave accent
É capital E, acute accent
Ê capital E, circumflex accent
Ë capital E, dieresis or umlaut mark
Ì capital I, grave accent
Í capital I, acute accent
Î capital I, circumflex accent
Ï capital I, dieresis or umlaut mark
Ð capital Eth, Icelandic
Ñ capital N, tilde
Ò capital O, grave accent
Ó capital O, acute accent
Ô capital O, circumflex accent
Õ capital O, tilde
Ö capital O, dieresis or umlaut mark
Ø capital O, slash
Ù capital U, grave accent
Ú capital U, acute accent
Û capital U, circumflex accent
Ü capital U, dieresis or umlaut mark
Ý capital Y, acute accent
Þ capital thorn, Icelandic
ß small sharp s, German
à small a, grave accent
á small a, acute accent
â small a, circumflex accent
ã small a, tilde
ä small a, dieresis or umlaut mark
å small a, ring
æ small ae diphthong
ç small c, cedilla
è small e, grave accent
é small e, acute accent
ê small e, circumflex accent
ë small e, dieresis or umlaut mark
ì small i, grave accent
í small i, acute accent
î small i, circumflex accent
ï small i, dieresis or umlaut mark
ð small eth, Icelandic
ñ small n, tilde
ò small o, grave accent
ó small o, acute accent
ô small o, circumflex accent
õ small o, tilde
ö small o, dieresis or umlaut mark
ø small o, slash
ù small u, grave accent
ú small u, acute accent
û small u, circumflex accent
ü small u, dieresis or umlaut mark
ý small y, acute accent
þ small thorn, Icelandic
ÿ small y, dieresis or umlaut mark
